#!/bin/bash
I=1
for subnet in 'subnet-ID' 'subnet-ID'
do
        echo "creating ec2 instances $subnet..."
aws ec2 run-instances --launch-template LaunchTemplateId=ID --subnet-id $subnet --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=Testserver-'${I}'}]'
I=$((I+1))
done
